spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paopao
    username: root
    password: 123456

server:
  port: 8080

mybatis:
  type-aliases-package: com.xcy.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

